name 'dynatraceoneagent'
maintainer 'Luis Escobar'
maintainer_email 'ace@dynatrace.com'
license 'MIT'
description 'Installs the Dynatrace OneAgent.'
version '0.2.0'
chef_version '>= 14.0'
issues_url 'https://github.com/Dynatrace/Dynatrace-OneAgent-Chef/issues'
source_url 'https://github.com/Dynatrace/Dynatrace-OneAgent-Chef'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'opensuse'
supports 'oracle'
supports 'redhat'
supports 'ubuntu'
supports 'windows'